### ISSUE TITLE
[Feature Request] Custom filters that we can add

### ISSUE THREAD

**Issue by noobdesigner922** [0xCUB3/wBlock#10]
Could you add an option to add custom filters, like what can be done in uBlock and AdGuard for Mac?

**Comment by 0xCUB3** [comment]
Yep this is planned.

**Comment by mrp52** [comment]
Great app thanks so much for making it *and* releasing it as FOSS! Custom filters is the only thing missing for me and then I can drop AdGuard for Safari for good so really hope to see this added soon 🙏

**Comment by aayushbhatia06** [comment]
The app is heading in a direction that I like. However I would love if there was a roadmap posted somewhere here so upcoming features are easily trackable!

**Comment by 0xCUB3** [comment]
Added in 4c14432

**Comment by mrp52** [comment]
Ah I see there is no release available for this yet. Nevermind, I will try it out whenever the release is made. Cheers!

**Comment by 0xCUB3** [comment]
> > Added in [4c14432](https://github.com/0xCUB3/wBlock/commit/4c14432e35dc93bfafe5978e3b312e4b60973aec)
> 
> Is there a way to download a version with all the commits?

Unfortunately, no. You will either have to compile the app yourself or wait until the v0.2 release.
