### ISSUE TITLE
A couple of bugs with wBlock

### ISSUE THREAD

**Issue by student8281** [0xCUB3/wBlock#11]
1. If you open wBlock, then close the window with command + W, it gets rid of that specific window but wBlock can still be seen in the menu bar.
2. To open wBlock again, you'd first have to click wBlock icon in the dock, then press command + N.
3. If I have a wBlock window open in the foreground and I click the wBlock icon in the dock followed by command + N, it opens another window. Every time I repeat these steps, wBlock opens a new window each time.

**Comment by 0xCUB3** [comment]
Thank you for this! I think in future releases I'll have wBlock quit with Command + W, since there's no reason for the app to run in the background.

**Comment by 0xCUB3** [comment]
Fixed in [c954f02](https://github.com/0xCUB3/wBlock/commit/c954f02437f5f4aa91b778000834b055c8dbcd0d)

Thanks for your patience. A new release will be made soon.
