### ISSUE TITLE
Unable to quit wBlock after opening the logs menu

### ISSUE THREAD

**Issue by Ctrl-Alb** [0xCUB3/wBlock#12]
First of all, thank you for what you are doing, wBlock is very good even if it's the first beta version.
I noticed that when I tried to open the logs menu, I was unable to quit wBlock and I had to force quit it.
I hope this project will keep going :)

**Comment by 0xCUB3** [comment]
You have to press 'Escape' to close the log window for now. I will add a button to close it in the next release. For now, I'll merge this with an existing issue of the same problem.

**Comment by 0xCUB3** [comment]
(See #5)
