### ISSUE TITLE
no way out of LOGS

### ISSUE THREAD

**Issue by gittiery** [0xCUB3/wBlock#14]
on macOS Sequoia:

whenever you click and open the 'logs', the log viewer pops up and displays the logs fine. 
however,
once you do so, you realize there is **no way possible to close that popup window**, and because of this there is **no way to exit the app, except to force quit.** 

sorry if anyone pointed this out already. I looked quickly and did not see.

-fom

**Comment by 0xCUB3** [comment]
See #3
