### ISSUE TITLE
[Feature Request] Update all filters at once + question

### ISSUE THREAD

**Issue by TheKivster** [0xCUB3/wBlock#15]
When you try to update filters in the app, it forces you to manually select each one instead of automatically updating all of them. So a Refresh All button or something like that would be useful.

Side question: Do you recommend enabling all filters or just using the default filters?

**Comment by 0xCUB3** [comment]
I recommend enabling the default ones. You can't actually enable all of them because Apple has a 150k rule limit, which all the lists together would exceed. 

I'll fix the issue you mentioned in the next release.

**Comment by arjpar** [comment]
That's actually a great idea. It's already possible given the statistics printed by SafariConverterLib on conversion of the filter lists to Safari ContentBlocker format.

**Comment by 0xCUB3** [comment]
> > I recommend enabling the default ones. You can't actually enable all of them because Apple has a 150k rule limit, which all the lists together would exceed.
> > I'll fix the issue you mentioned in the next release.
> 
> Any idea if you’ll add an indicator warning the user if they have accidentally selected too many filters and are exceeding the 150K limit?

There already is such a warning. Hopefully it works ;) @arjpar

**Comment by 0xCUB3** [comment]
Merging this into #10
