### ISSUE TITLE
Error reloading content blocker

### ISSUE THREAD

**Issue by gmazzucchelli** [0xCUB3/wBlock#19]
macOS 15.1
Safari 18.1
<img width="812" alt="Screenshot 2024-11-14 alle 12 20 40" src="https://github.com/user-attachments/assets/3d2845a2-b015-4039-b300-9899b3a85576">
<img width="812" alt="Screenshot 2024-11-14 alle 12 20 44" src="https://github.com/user-attachments/assets/a2e68523-0b28-4fe0-af85-cabe6cf6dc33">

**Comment by 0xCUB3** [comment]
yeah this is because the person who signed the app didn't correctly rename all the app IDs, so the app is unable to access the filters extension. There is no code to fix but when he's available, we'll make another release with the correction made.
