### ISSUE TITLE
Blocking sign in prompt

### ISSUE THREAD

**Issue by gmazzucchelli** [0xCUB3/wBlock#20]
Wondering if wBlock would be able to block sign in prompts, as on Facebook or LinkedIn and, in case, with which filter list.

**Comment by 0xCUB3** [comment]
There are filter lists for that but I haven't added them. It's something I can try to add in the next release.

**Comment by gmazzucchelli** [comment]
Tested AdGuard Social Media Filter before opening this issue, but no success. 
Also, cleared cache and cookies, before applying new filtering rules.

**Comment by 0xCUB3** [comment]
Alright I'll investigate this more.

**Comment by arjpar** [comment]
If it's not blocking the sign in prompts it's either an issue with the filter list or with how wBlock is converting the content blocker or executing the js
