### ISSUE TITLE
The same filters show up more than once when updating

### ISSUE THREAD

**Issue by TheKivster** [0xCUB3/wBlock#25]
When updating, the list of filters sometimes appears more than once. This doesn't seem to affect the use of the app and is just a visual glitch.
![wBlock Glitch](https://github.com/user-attachments/assets/475ec24f-5687-4b6f-b398-6713d01b075d)

**Comment by 0xCUB3** [comment]
yeah this will be fixed in the next release. It was a very silly bug. It's already written in the code so I'm closing this issue
