### ISSUE TITLE
No releases

### ISSUE THREAD

**Issue by fanckush** [0xCUB3/wBlock#3]
hey! were can I find the extension?
Or do I have to built it myself?

**Comment by 0xCUB3** [comment]
Unfortunately, you have to build it yourself and I'll explain why.

Apple has very strict restrictions against extensions using permissions in the app sandbox. Therefore, since I do not have a paid Apple developer account, the extension does not work at all for users outside of my local machine.

I'm trying to find actively somebody to sign my app with a paid account because unfortunately $99 a year is not in the cards for me as a student.

The app should be stable enough to try to build yourself, however.

**Comment by fanckush** [comment]
makes total sense, i'll build it myself then.

I don't have an paid dev account but I might in the near future, if I do that, i'll be happy to help with that part

**Comment by 0xCUB3** [comment]
Thank you! That would be greatly appreciated :)

**Comment by Mihuy1** [comment]
@0xCUB3 Probably would be a good idea to add this to README while you don't have the paid dev account? (unless I'm just blind as usual and didn't see it)

**Comment by Svec-Tomas** [comment]
Thank you for creating this free and open source project!

I have a few questions:

1. Until a downloadable build is available from releases, could you please share instructions on how to build it myself?

2. As a moderator on r/macapps, I'm confident that raising the necessary funds for the annual Apple developer fee would take only a few hours. I'd be happy to contribute to this effort.

3. I'd also be delighted to help make this app available in my native language if you're open to adding multilingual support.

**Comment by 0xCUB3** [comment]
Hi @Svec-Tomas, if you'd be willing to raise those funds then that would be great, but I'm not expecting anything from anyone.

Building the app is a bit of an involved process too complex for a GitHub issue, but there are plenty of tutorials on the internet. 

As for the native language, let's stick with English until the app is a bit more stable. Localization complicates things a bit.

**Comment by khurshid-alam** [comment]
@0xCUB3 

Sandbox app restriction can be overwritten who doesn’t use SIP. Kindly provide a dmg for apple silicon. 

Thanks.

**Comment by 0xCUB3** [comment]
most people don't have SIP disabled. If I make a release, I will immediately get 1000 issues about "why doesn't the app work???" because of apple quarantining the extension containers.

**Comment by khurshid-alam** [comment]
Ah ok. Make sense. But can upload here without release ?

**Comment by 0xCUB3** [comment]
@khurshid-alam here you go :) good luck! 

[wBlock.zip](https://github.com/user-attachments/files/16919881/wBlock.zip)
