### ISSUE TITLE
Request to add Chinese filter.

### ISSUE THREAD

**Issue by cweijan** [0xCUB3/wBlock#6]
Hi, I'm glad to see you released v0.1. It works very well, but because there are no Chinese filters, ad blocking doesn’t work well on Chinese sites. please consider supporting it!

https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_224_Chinese/filter.txt

<img width="1062" alt="image" src="https://github.com/user-attachments/assets/56e70977-36b4-45aa-8903-9526b14c8ec6">

**Comment by 0xCUB3** [comment]
Ooh I'll definitely add these! I had general blocking in mind for the first release, but foreign language filters definitely should also be added.

**Comment by cweijan** [comment]
Thanks!

**Comment by 0xCUB3** [comment]
I'm keeping this issue open until I implement the change in case others have a similar question

**Comment by 0xCUB3** [comment]
How is this? :) 
Chinese is at the bottom, not in picture.
![CleanShot 2024-10-13 at 17 08 47](https://github.com/user-attachments/assets/c11558da-0baf-4519-9aa4-7deac6110dd9)

**Comment by 0xCUB3** [comment]
Fixed in [fd83279](https://github.com/0xCUB3/wBlock/commit/fd83279fb908bc14995e61f4251e4b57597e5e30)
