### ISSUE TITLE
Data access permission nagging

### ISSUE THREAD

**Issue by meshuggah44** [0xCUB3/wBlock#8]
macOS version: 15.0.1

wBlock version: 0.1.0

Whenever I open Safari and/or wBlock, as well as the first website of that browsing session, wBlock asks me for data access permission even though I've already given it on Safari's settings.

Here's a [video](https://www.capster.io/video/mzmmdTWQoJXN) of the behaviour.

**Comment by 0xCUB3** [comment]
> Same here. macOS version: 15.0.1 wBlock version: 0.1.0
> 
> **Edit:** I don't know if this is related but app logs show me this:
> 
> ```
> Successfully wrote blockerList.json
> Successfully wrote advancedBlocking.json
> Attempting to reload content blocker with 101080 rules
> Error reloading content blocker: Error Domain=SFErrorDomain Code=1 "(null)"
> ```

interesting... @emikaadeo-git can you list which blocklists you have toggled on?

**Comment by 0xCUB3** [comment]
I think the reloading error is due to the fact that I have the data in an ID attributed to my apple id, while someone else is signing the app. I'll make sure that part is fixed in the next release.

**Comment by circlePulse** [comment]
When can we expect that next release?

**Comment by 0xCUB3** [comment]
We can expect it when I figure out how to fix it.

**Comment by chungweileong94** [comment]
Not too familiar with the Mac App development, but apparently if you give wblock full disk access, which will give wblock full data access to safari, and it will stop asking you the permission again.

@0xCUB3 Good extension btw👏

**Comment by 0xCUB3** [comment]
> Not too familiar with the Mac App development, but apparently if you give wblock full disk access, which will give wblock full data access to safari, and it will stop asking you the permission again.
> 
> @0xCUB3 Good extension btw👏

this is a great idea, but in order to give full disk access, I need to disable App Sandbox. This is not allowed for Safari extensions. I need to figure out how other ad blockers are doing this...

**Comment by auntchilada** [comment]
> > Not too familiar with the Mac App development, but apparently if you give wblock full disk access, which will give wblock full data access to safari, and it will stop asking you the permission again.
> > @0xCUB3 Good extension btw👏
> 
> this is a great idea, but in order to give full disk access, I need to disable App Sandbox. This is not allowed for Safari extensions. I need to figure out how other ad blockers are doing this...


chungweileong94 is referring to the setting is System Settings.app pane

  [ Privacy & Security ] > [ Full Disk Access ] > wBlock (o ) toggle

enabling that item fixes the access permissions dialog from appearing.

tested here and it appears to work.

so, you don't have to chase down how to code it, but perhaps some way of detecting that knob needs to be frobbed and directing the user to enable full disk access for the extension.

regards,

auntchiladaz

**Comment by meshuggah44** [comment]
Although it's a workaround, it's really not recommended to give full disk access to apps or Safari extensions in general. It might be fine in wBlock's case, but it's bad practice and you might stumble upon a rogue app sooner or later

**Comment by auntchilada** [comment]
agreed, i don't think wBlock should have wholesale access, but reporting the issue might offer some insights about it ;-]

**Comment by 0xCUB3** [comment]
At this point I don't know how to solve this problem without having to ask for full disk access, since I store the blocklists on the user's mac, which requires full disk access in order to read and write to them. I'm not sure how other blockers circumvent this.

**Comment by 0xCUB3** [comment]
Should be fixed in 78569d1
